DROP TABLE IF EXISTS `meet`;

CREATE TABLE `meet` (
  `id` mediumint(9) NOT NULL AUTO_INCREMENT,
  `name` varchar(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=latin1;

LOCK TABLES `meet` WRITE;
INSERT INTO `meet` VALUES (0, 'test meet');
UNLOCK TABLES;
