version: '3.6'
services:
  api:
    build: .
    image: gymnastics-api
    restart: always
    ports:
      - 8000:8000
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306

  mysql:
    image: mysql:5
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init/meet-init.sql/docker-entrypoint-initdb.d
      - ./db-init/team-init.sql/docker-entrypoint-initdb.d
      - ./db-init/player-init.sql/docker-entrypoint-initdb.d
      - ./db-init/judge-init.sql/docker-entrypoint-initdb.d
      - ./db-init/score-init.sql/docker-entrypoint-initdb.d
      - ./db-init/lineup-init.sql/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}


volumes:
  mysql-data:
    name: gymnastics-mysql-data
